apiVersion: v1
kind: Pod
metadata:
  name: from-configmap
spec:
  containers:
  - name: nginx
    image: nginx
  env:
  - name: CONFIGMAP_USERNAME
    valueFrom:
      configMapKeyRef:
        name: config
        key: username

      
