apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
  labels:
    project: for-deploy
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      project: for-deploy
      env: dev
  template:
  metadata:
    name: deployement
    labels:
      app: nginx
      project: for-deploy
      env: dev
  spec:
    containers:
    - name: nginx
      image: nginx

    