apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
spec:
  type: LoadBalancer
  selector:
    environment: "dev"
    course: "aws"
  ports:
  - name: nginx
    protocol: TCP
    port: 80 
    targetPort: 80
    nodePort: 30007