apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replic
  labels:
    env: dev
    replica: created
spec:
  replicas: 3 #3 pods created
  selector:
    matchLabels:
      tier: app
      project: expense
      replicaset: created
  template:
    metadata:
      labels:
        tier: app
        project: expense
        replicaset: created
    spec:
      containers:
      - name: nginx
        image: nginx
