apiVersion: v1
kind: ReplicaSet
metadata:
  name: replic
  labels:
    env: dev
    replica: yes
spec:
  replicas: 3 #3 pods created
  selector:
    matchLabels:
      tier: app
      project: expense
      replicaset: yes
  template:
    metadata:
      labels:
        tier: app
        project: expense
        replicaset: yes
    spec:
      containers:
      - name: nginx
        image: nginx
